name: Dependency Submission
on:
  workflow_call:
    secrets:
      ssh_private_key:
        required: true

permissions:
  contents: write
jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Java with Gradle
      uses: interact-io/github-actions/actions/setup-java-gradle@master
      with:
        submodules: 'true'
        ssh-key: ${{ secrets.ssh_private_key }}
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v6
